version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-seuUsuario}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-suaSenha}
      POSTGRES_DB: ${POSTGRES_DB:-seuBanco}
    volumes:
      - db_data:/var/lib/postgresql/data



  app:
    image: raphaba9/restfulapi-app
    container_name: python_app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db
