version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: python_app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cloud
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
