version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-cloud}
    networks:
      - restfulapi-network

  app:
    image: raphaba9/restfulapi-app:latest
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-cloud}"
      SECRET_KEY: "SuperHiperMegaChaveSecreta123123"
      ALGORITHM: "HS256"
    restart: always
    networks:
      - restfulapi-network

networks:
  restfulapi-network:
