services:
  db:
    image: postgres:15
    container_name: postgres_db
    # ports:
    #   - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
      POSTGRES_DB: ${POSTGRES_DB:-projeto}
    networks:
      - restfulapi-network

  app:
    image: raphaba9/restfulapi-app:latest
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://${POSTGRES_USER:-projeto}:${POSTGRES_PASSWORD:-projeto}@db:5432/${POSTGRES_DB:-projeto}
      SECRET_KEY: "${SECRET_KEY:-superChaveSecretaUau}"
      ALGORITHM: "HS256"
    restart: always
    networks:
      - restfulapi-network


networks:
  restfulapi-network: