services:
  app:
    image: raphaba9/restfulapi-app
    container_name: python_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-seuUsuario}:${POSTGRES_PASSWORD:-suaSenha}@db:5432/${POSTGRES_DB:-suaBase}
      SECRET_KEY: "${SECRET_KEY:-superChaveSecretaUau}"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-seuUsuario}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-suaSenha}
      POSTGRES_DB: ${POSTGRES_DB:-suaBase}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
