apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: raphaba9/webdeploy:v3
        env:
          - name: SQLALCHEMY_DATABASE_URL
            value: "postgresql://postgres:admin@postgres:5432/cloud"
          - name: SECRET_KEY
            value: "SuperHiperMegaChaveSecreta123123"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fastapi
